HelloMVC/Models/Product.cs
using System.Collections.Generic;

namespace HelloMVC.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string DisplaySubject { get; set; }
        public string Name { get; set; }
        public string ModelName { get; set; }
        public string SerialNo { get; set; }
        public string ItemModelNo { get; set; }
        public string WebSite { get; set; }
        public decimal Weight { get; set; }

        public Dimension Dimension { get; set; }
        
        public Category Category { get; set; }
        public Category SubCategory { get; set; }

        public List<Tag> Tags { get; set; }

        public PurchaseDetail PurchaseDetail { get; set; }
        public List<ServiceRepairDetail> ServiceRepairDetails { get; set; }
        public List<PreviousOwner> PreviousOwners { get; set; }
    }
}

HelloMVC/Controllers/PreviousOwnerController.cs
using System.Data;
using System.Linq;
using System.Web.Mvc;
using HelloMVC.Models;
using HelloMVC.DAL;

namespace HelloMVC.Controllers
{
    public class PreviousOwnerController : Controller
    {
        private readonly SaleContext db = new SaleContext();

        //
        // GET: /PreviousOwner/

        public ActionResult Index()
        {
            return View(db.PreviousOwners.ToList());
        }

        //
        // GET: /PreviousOwner/Details/5

        public ActionResult Details(int id = 0)
        {
            PreviousOwner previousowner = db.PreviousOwners.Find(id);
            if (previousowner == null)
            {
                return HttpNotFound();
            }
            return View(previousowner);
        }

        //
        // GET: /PreviousOwner/Create

        public PartialViewResult Create()
        {
            return PartialView();
        }

        //
        // POST: /PreviousOwner/Create

        //[HttpPost]
        //public ActionResult Create(PreviousOwner previousowner)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.PreviousOwners.Add(previousowner);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(previousowner);
        //}

        //
        // GET: /PreviousOwner/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PreviousOwner previousowner = db.PreviousOwners.Find(id);
            if (previousowner == null)
            {
                return HttpNotFound();
            }
            return View(previousowner);
        }

        //
        // POST: /PreviousOwner/Edit/5

        [HttpPost]
        public ActionResult Edit(PreviousOwner previousowner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(previousowner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(previousowner);
        }

        //
        // GET: /PreviousOwner/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PreviousOwner previousowner = db.PreviousOwners.Find(id);
            if (previousowner == null)
            {
                return HttpNotFound();
            }
            return View(previousowner);
        }

        //
        // POST: /PreviousOwner/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PreviousOwner previousowner = db.PreviousOwners.Find(id);
            db.PreviousOwners.Remove(previousowner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HelloMVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelloMVC.Models;
using HelloMVC.DAL;

namespace HelloMVC.Controllers
{
    public class ProductController : Controller
    {
        private SaleContext db = new SaleContext();

        //
        // GET: /Product/

        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        //
        // GET: /Product/Details/5

        public ActionResult Details(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // GET: /Product/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Product/Create

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        //
        // GET: /Product/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        public ActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        //
        // GET: /Product/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        //
        // POST: /Product/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HelloMVC/Controllers/PurchaseDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelloMVC.Models;
using HelloMVC.DAL;

namespace HelloMVC.Controllers
{
    public class PurchaseDetailController : Controller
    {
        private SaleContext db = new SaleContext();

        //
        // GET: /PurchaseDetail/

        public ActionResult Index()
        {
            return View(db.PurchaseDetails.ToList());
        }

        //
        // GET: /PurchaseDetail/Details/5

        public ActionResult Details(int id = 0)
        {
            PurchaseDetail purchasedetail = db.PurchaseDetails.Find(id);
            if (purchasedetail == null)
            {
                return HttpNotFound();
            }
            return View(purchasedetail);
        }

        //
        // GET: /PurchaseDetail/Create

        public PartialViewResult Create()
        {
            return PartialView();
        }

        //
        // POST: /PurchaseDetail/Create

        //[HttpPost]
        //public ActionResult Create(PurchaseDetail purchasedetail)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.PurchaseDetails.Add(purchasedetail);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(purchasedetail);
        //}

        //
        // GET: /PurchaseDetail/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PurchaseDetail purchasedetail = db.PurchaseDetails.Find(id);
            if (purchasedetail == null)
            {
                return HttpNotFound();
            }
            return View(purchasedetail);
        }

        //
        // POST: /PurchaseDetail/Edit/5

        [HttpPost]
        public ActionResult Edit(PurchaseDetail purchasedetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(purchasedetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(purchasedetail);
        }

        //
        // GET: /PurchaseDetail/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PurchaseDetail purchasedetail = db.PurchaseDetails.Find(id);
            if (purchasedetail == null)
            {
                return HttpNotFound();
            }
            return View(purchasedetail);
        }

        //
        // POST: /PurchaseDetail/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PurchaseDetail purchasedetail = db.PurchaseDetails.Find(id);
            db.PurchaseDetails.Remove(purchasedetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HelloMVC/Controllers/ServiceRepairController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelloMVC.Models;
using HelloMVC.DAL;

namespace HelloMVC.Controllers
{
    public class ServiceRepairController : Controller
    {
        //private SaleContext db = new SaleContext();

        ////
        //// GET: /ServiceRepair/

        //public ActionResult Index()
        //{
        //    return View(db.ServiceRepairDetails.ToList());
        //}

        ////
        //// GET: /ServiceRepair/Details/5

        //public ActionResult Details(int id = 0)
        //{
        //    ServiceRepairDetail servicerepairdetail = db.ServiceRepairDetails.Find(id);
        //    if (servicerepairdetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(servicerepairdetail);
        //}

        //
        // GET: /ServiceRepair/Create

        public PartialViewResult Create()
        {
            return PartialView();
        }

        //
        // POST: /ServiceRepair/Create

        //[HttpPost]
        //public ActionResult Create(ServiceRepairDetail servicerepairdetail)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.ServiceRepairDetails.Add(servicerepairdetail);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(servicerepairdetail);
        //}

        //
        // GET: /ServiceRepair/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    ServiceRepairDetail servicerepairdetail = db.ServiceRepairDetails.Find(id);
        //    if (servicerepairdetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(servicerepairdetail);
        //}

        ////
        //// POST: /ServiceRepair/Edit/5

        //[HttpPost]
        //public ActionResult Edit(ServiceRepairDetail servicerepairdetail)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(servicerepairdetail).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(servicerepairdetail);
        //}

        ////
        //// GET: /ServiceRepair/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    ServiceRepairDetail servicerepairdetail = db.ServiceRepairDetails.Find(id);
        //    if (servicerepairdetail == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(servicerepairdetail);
        //}

        ////
        //// POST: /ServiceRepair/Delete/5

        //[HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    ServiceRepairDetail servicerepairdetail = db.ServiceRepairDetails.Find(id);
        //    db.ServiceRepairDetails.Remove(servicerepairdetail);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    db.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

HelloMVC/Views/Product/Create.cshtml
@using HelloMVC.Models
@model HelloMVC.Models.Product

@{
    ViewBag.Title = "Product Details";
}

<h2>Product Details</h2>

@using (Html.BeginForm("Create", "Product")) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Product</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.DisplaySubject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DisplaySubject)
            @Html.ValidationMessageFor(model => model.DisplaySubject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelName)
            @Html.ValidationMessageFor(model => model.ModelName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SerialNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SerialNo)
            @Html.ValidationMessageFor(model => model.SerialNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemModelNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ItemModelNo)
            @Html.ValidationMessageFor(model => model.ItemModelNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.WebSite)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebSite)
            @Html.ValidationMessageFor(model => model.WebSite)
        </div>
        
            @Html.LabelFor(model => model.Weight)
        <div class="editor-label">
            @Html.EditorFor(model => model.Weight)
            @Html.ValidationMessageFor(model => model.Weight)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Dimension.Width)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dimension.Width)
            @Html.ValidationMessageFor(model => model.Dimension.Width)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Dimension.Height)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dimension.Height)
            @Html.ValidationMessageFor(model => model.Dimension.Height)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Dimension.Depth)
        </div>
        <div class="editor-field">
            
            @Html.EditorFor(model => model.Dimension.Depth)
            @Html.ValidationMessageFor(model => model.Dimension.Depth)
        </div>
        
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Category.Name, Enumerable.Empty<SelectListItem>())
            @Html.ValidationMessageFor(model => model.Category.Name)
        </div>

        <div class="editor-field">
            @Html.DropDownListFor(model => model.SubCategory.Name, Enumerable.Empty<SelectListItem>())
            @Html.ValidationMessageFor(model => model.SubCategory.Name)
        </div>

        @{
            Html.RenderAction("Create", "PurchaseDetail");
            Html.RenderAction("Create", "PreviousOwner"); 
            Html.RenderAction("Create", "ServiceRepair");
        }
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HelloMVC/Views/Product/Delete.cshtml
@model HelloMVC.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Product</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DisplaySubject)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DisplaySubject)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModelName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModelName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SerialNo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SerialNo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ItemModelNo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ItemModelNo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebSite)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebSite)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Weight)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Weight)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

HelloMVC/Views/Product/Details.cshtml
@model HelloMVC.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Product</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DisplaySubject)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DisplaySubject)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ModelName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ModelName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SerialNo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SerialNo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ItemModelNo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ItemModelNo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.WebSite)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.WebSite)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Weight)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Weight)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ProductId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HelloMVC/Views/Product/Edit.cshtml
@model HelloMVC.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Product</legend>

        @Html.HiddenFor(model => model.ProductId)

        <div class="editor-label">
            @Html.LabelFor(model => model.DisplaySubject)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DisplaySubject)
            @Html.ValidationMessageFor(model => model.DisplaySubject)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ModelName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ModelName)
            @Html.ValidationMessageFor(model => model.ModelName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SerialNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SerialNo)
            @Html.ValidationMessageFor(model => model.SerialNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ItemModelNo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ItemModelNo)
            @Html.ValidationMessageFor(model => model.ItemModelNo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.WebSite)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebSite)
            @Html.ValidationMessageFor(model => model.WebSite)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Weight)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Weight)
            @Html.ValidationMessageFor(model => model.Weight)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HelloMVC/Views/Product/Index.cshtml
@model IEnumerable<HelloMVC.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DisplaySubject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModelName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SerialNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemModelNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebSite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DisplaySubject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModelName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SerialNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemModelNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WebSite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
        </td>
    </tr>
}

</table>